import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNavbar from "@/components/TopNavbar"
import { ThemeProvider } from "@/components/theme-provider"
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { SocketProvider } from "../lib/SocketProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <SocketProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider>

              <div className="flex min-h-screen w-full">
                <AppSidebar />

                <div className="flex flex-1 flex-col">
                  <TopNavbar />

                  <main className="flex-1 overflow-auto p-4">
                    {children}
                  </main>
                </div>
              </div>

            </SidebarProvider>
          </ThemeProvider>
        </body>
      </SocketProvider>
    </html>
  );
}